#!/bin/bash

echo "🔍 Debugging Story Access Issue"
echo "================================"
echo ""

STORY_ID="M9cCXqc2QCcir5lhoKRWP"

echo "Story ID: $STORY_ID"
echo ""

# Instructions for getting session token
echo "📝 Steps to debug:"
echo "=================="
echo ""
echo "1. Open https://synqforge.com in your browser"
echo "2. Make sure you're logged in"
echo "3. Open DevTools (F12) → Application → Cookies"
echo "4. Find cookie: '__Secure-next-auth.session-token' or 'next-auth.session-token'"
echo "5. Copy the cookie value"
echo ""
echo "6. Then run this command with your session token:"
echo ""
echo "   curl -H 'Cookie: __Secure-next-auth.session-token=YOUR_TOKEN_HERE' \\"
echo "        https://synqforge.com/api/stories/$STORY_ID"
echo ""
echo "This will show the actual API response."
echo ""
echo "---"
echo ""
echo "📊 What to look for in the response:"
echo "===================================="
echo ""
echo "✅ Success: Returns story JSON with 200 status"
echo "❌ 404: Story not found in database"
echo "❌ 403: Access denied - org mismatch"
echo "❌ 500: Server error - check Vercel logs"
echo ""
echo "---"
echo ""
echo "🔎 Check Vercel logs for more details:"
echo "======================================"
echo ""
echo "   vercel logs --prod --follow"
echo ""
echo "   # Or view in dashboard:"
echo "   # https://vercel.com/[your-username]/synqforge/logs"
echo ""
echo "Look for errors like:"
echo "  - 'Story not found'"
echo "  - 'Access denied'"
echo "  - 'Database error'"
echo "  - SQL query errors"
echo ""
