import { FlatCompat } from '@eslint/eslintrc'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const compat = new FlatCompat({ baseDirectory: __dirname })

const config = [
  // Ignore build/output
  { ignores: ['.next/**', 'node_modules/**', '.vercel/**'] },

  // Bring in legacy shareable configs (Next.js + TS)
  ...compat.extends('next/core-web-vitals', 'plugin:@typescript-eslint/recommended'),

  // Silence a Next-generated file (autogenerated; safe to ignore this rule here)
  {
    files: ['next-env.d.ts'],
    rules: { '@typescript-eslint/triple-slash-reference': 'off' }
  },

  // Project rules (relaxed so you can build now; tighten later)
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'react-hooks/exhaustive-deps': 'warn',
      'react/no-unescaped-entities': 'off',
      '@next/next/no-img-element': 'off',
      'react/forbid-dom-props': 'off'
    }
  }
]

export default config
